# Mushroom Dataset
created by krohak 2018-01-23

In [1]:
import numpy as np
import pandas as pd
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
import graphviz


pddata = pd.read_csv('agaricus-lepiota.data')

print(pddata.head())

le = preprocessing.LabelEncoder()

for col in pddata.columns.values:
        uniq_label=list(pddata[col].unique())
        #print(uniq_label)
        le_fitted = le.fit(uniq_label)
        pddata[col] = le.transform(list(pddata[col].values))

print(pddata.head())
print(pddata.shape)

   p  x  s  n  t p.1  f  c n.1  k ... s.2  w w.1 p.2 w.2  o p.3 k.1 s.3  u
0  e  x  s  y  t   a  f  c   b  k ...   s  w   w   p   w  o   p   n   n  g
1  e  b  s  w  t   l  f  c   b  n ...   s  w   w   p   w  o   p   n   n  m
2  p  x  y  w  t   p  f  c   n  n ...   s  w   w   p   w  o   p   k   s  u
3  e  x  s  g  f   n  f  w   b  k ...   s  w   w   p   w  o   e   n   a  g
4  e  x  y  y  t   a  f  c   b  n ...   s  w   w   p   w  o   p   k   n  g

[5 rows x 23 columns]
   p  x  s  n  t  p.1  f  c  n.1  k ...  s.2  w  w.1  p.2  w.2  o  p.3  k.1  \
0  0  5  2  9  1    0  1  0    0  4 ...    2  7    7    0    2  1    4    3   
1  0  0  2  8  1    3  1  0    0  5 ...    2  7    7    0    2  1    4    3   
2  1  5  3  8  1    6  1  0    1  5 ...    2  7    7    0    2  1    4    2   
3  0  5  2  3  0    5  1  1    0  4 ...    2  7    7    0    2  1    0    3   
4  0  5  3  9  1    0  1  0    0  5 ...    2  7    7    0    2  1    4    2   

   s.3  u  
0    2  1  
1    2  3  
2    3  5  
3   

In [2]:
df1=pd.DataFrame(index=pddata.index)
df1=df1.join(pddata)

In [3]:
df1.head()

p  x  s  n  t  p.1  f  c  n.1  k ...  s.2  w  w.1  p.2  w.2  o  p.3  k.1  \
0  0  5  2  9  1    0  1  0    0  4 ...    2  7    7    0    2  1    4    3   
1  0  0  2  8  1    3  1  0    0  5 ...    2  7    7    0    2  1    4    3   
2  1  5  3  8  1    6  1  0    1  5 ...    2  7    7    0    2  1    4    2   
3  0  5  2  3  0    5  1  1    0  4 ...    2  7    7    0    2  1    0    3   
4  0  5  3  9  1    0  1  0    0  5 ...    2  7    7    0    2  1    4    2   

   s.3  u  
0    2  1  
1    2  3  
2    3  5  
3    0  1  
4    2  1  

[5 rows x 23 columns]

In [4]:
pddata = df1
Y_train = pddata.values[0:7000,0] # col 0 is the class label
X_train = pddata.values[0:7000,1:22] # the remaining columns are data
Y_test = pddata.values[7001:, 0]
X_test = pddata.values[7001:, 1:22]

print(X_train[0:5])
print(Y_train[0:5])

[[5 2 9 1 0 1 0 0 4 0 2 2 2 7 7 0 2 1 4 3 2]
 [0 2 8 1 3 1 0 0 5 0 2 2 2 7 7 0 2 1 4 3 2]
 [5 3 8 1 6 1 0 1 5 0 3 2 2 7 7 0 2 1 4 2 3]
 [5 2 3 0 5 1 1 0 4 1 3 2 2 7 7 0 2 1 0 3 0]
 [5 3 9 1 0 1 0 0 5 0 2 2 2 7 7 0 2 1 4 2 2]]
[0 0 1 0 0]


In [5]:
clf=DecisionTreeClassifier() # define a new classifier clf


#clf=GaussianNB()

clf=clf.fit(X_train, Y_train) # perform training

#dot_data = tree.export_graphviz(clf, out_file="mush.png")
#graph = graphviz.Source(dot_data)
#graph.render("mushroom")

Y_predict = clf.predict(X_test)

print(accuracy_score(Y_test, Y_predict)*100)

100.0
